#!/bin/bash -l 
#SBATCH --time=24:00:00  
#SBATCH --job-name=fold_1_batch_64
#SBATCH --export=NONE 
#SBATCH --nodes=1
#SBATCH --gres=gpu:1

unset SLURM_EXPORT_ENV

module add python
conda activate lol

export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export http_proxy=http://proxy:80
export https_proxy=http://proxy:80
export LD_PRELOAD=$CONDA_PREFIX/lib/libstdc++.so.6

python3 /home/vault/iwi5/iwi5207h/metric_learning_ds_new/run_train.py